### ISSUE TITLE
"The error was: slideshow" Can't view slides on nbviewer.

### ISSUE THREAD

**Issue by basnijholt** [jupyter/nbviewer#466]
I've made my nb with proper markup, but on nbviewer.ipython.org I'm not able to view the slides.

Notebook:
http://nbviewer.ipython.org/gist/basnijholt/2e9aa58de39a07943dd3

and slides:
http://nbviewer.ipython.org/format/slides/gist/basnijholt/2e9aa58de39a07943dd3

The error message is not very clear.

**Comment by bollwyvl** [comment]
Curious indeed! Works now though, right? I could not reproduce the error.

Did you change the doc since you got the error? That error sounds like
somebody (nbviewer or nbconvert) was looking in metadata, and wasn't
handling the case where there is no slide meta.

Will look into it this weekend.

**Comment by basnijholt** [comment]
Yes I did update it, I've restored it to the previous version.

**Comment by bollwyvl** [comment]
can't reproduce the issue locally.

can you put the good and bad things up on gists or some other immutable URL
so that we have something to compare? you can just drag them into
https://gist.github.com

**Comment by basnijholt** [comment]
Here it is: 

https://gist.github.com/basnijholt/2e9aa58de39a07943dd3

converting it with nbconvert to slides works fine btw.

**Comment by bollwyvl** [comment]
Minimal case is here:

https://gist.github.com/9a387ff6c870a59889c2.git

http://nbviewer.ipython.org/format/slides/gist/anonymous/9a387ff6c870a59889c2

The issue appears to be following a fragment with a cell that has never had a slide type set.

The nickle fix for this and #469 is to manually fiddle every cell with slide type `-` to be something else and back to `-`... sorry about that. 

Issue appears to be upstream, very likely related to https://github.com/ipython/ipython/pull/8415 since we have never encountered this before now.

Will work on a fix, and link back here.

**Comment by bollwyvl** [comment]
Created the upstream, future issue and simplest PR. Will be discussed there, then backported to ipython/3.x.

Because nbviewer uses the docker container built from `3.x`, as soon as that is merged and nbviewer is redployed, the fix should be in, but it will likely be a few days!

Thanks again @basnijholt and @cranmer.

**Comment by damianavila** [comment]
Thanks @bollwyvl for the catch! I have already reviewed your PR.
@basnijholt, @cranmer, this should be solved soon...

**Comment by cranmer** [comment]
Thanks everyone!

**Comment by bollwyvl** [comment]
With the most recent deploy for #471 and friends, this is still an issue on production:
http://nbviewer.ipython.org/format/slides/gist/anonymous/9a387ff6c870a59889c2

The nbconvert fix has been in on the upstream 3.x branch for some time. I'm (slowly) pulling the most recent `ipython/ipython:3.x` to verify, but my guess is this is an issue of the production docker container being out of date.

Could be we'll be going to 4.x, jupyter, etc. imminently, so it may not be worth digging around too much...

**Comment by bollwyvl** [comment]
Looking at another comment by @rgbkrk, it was suggested this could be a fastly cache issue: i just made a new fork of the above gist, and am still seeing the issue:
http://nbviewer.ipython.org/format/slides/gist/bollwyvl/2e3d323fc2a4d3147d33

(also still pulling the docker container...)

**Comment by rgbkrk** [comment]
When I click that notebook link, the git hash at the bottom is really recent - it doesn't appear to be a fastly issue.

**Comment by damianavila** [comment]
It is a nbconvert issue, the fix is here, but I have to investigate a little more to see if I am not breaking other things... I will push a PR soon:

```diff
 git diff ../../preprocessors/revealhelp.py
diff --git a/nbconvert/preprocessors/revealhelp.py b/nbconvert/preprocessors/revealhelp.py
index 82aab2a..c21fb07 100755
--- a/nbconvert/preprocessors/revealhelp.py
+++ b/nbconvert/preprocessors/revealhelp.py
@@ -53,7 +53,7 @@ class RevealHelpPreprocessor(Preprocessor):
                     # We need to break the loop when a new slide or subslide is
                     # found to avoid the propagation of the data-fragment-index
                     # across multiple slides/subslides
-                    if nb.cells[index + i].metadata.slideshow.slide_type in ['slide', 'subslide']:
+                    if nb.cells[index + i].metadata.slide_type in ['slide', 'subslide']:
                         break
                     else:
                         nb.cells[index + i].metadata.frag_helper = 'fragment_end'
```

**Comment by bollwyvl** [comment]
Hooray, fixed in production. Please open new issues if you experience additional problems!

**Comment by cranmer** [comment]
thanks!

**Comment by jakirkham** [comment]
I think I am also experiencing this issue or perhaps I have incorrectly built my notebook. Here it is ( https://github.com/DudLab/git_ready/blob/master/slides.ipynb ). I am able to get it to render locally. It may simply be that `nbviewer` has an outdated cached version.

**Comment by bollwyvl** [comment]
Yep, looks fine from this side:

http://nbviewer.ipython.org/format/slides/github/DudLab/git_ready/blob/master/slides.ipynb#/

Nice content: I wonder, would it be even more interesting with an actual
repo backing it, and use of the "!" magic? I've seen a number of examples
of sites that do this for tutorials.

**Comment by damianavila** [comment]
> Nice content: I wonder, would it be even more interesting with an actual
repo backing it, and use of the "!" magic? I've seen a number of examples
of sites that do this for tutorials.

A bash kernel + tmpnb + RISElet and you have live slides showing your content...

**Comment by jakirkham** [comment]
Alright, sorry, I'm a fool. It would help if I pushed the view as slides button. ;)

Thanks. Interesting. Something to think about. Maybe using a submodule?

I had these slides in PowerPoint before and thought I need a better way to share these. So, I tried out the notebook, which looks great.

One comment though. My content gets a little long to fit on a page. I suppose I could hack it down, but I was trying to demonstrate each step. Is there someway that we might be able to scroll with the nbviewer. I know have been able to do this locally. Is it just a matter of update the versions online or is there a little more to it?

**Comment by damianavila** [comment]
well, at some time we enabled the scroll on nbviewer... but maybe it is not working again (it breaks with frequency)... ping @bollwyvl

**Comment by damianavila** [comment]
@jakirkham latest version of nbconvert should be able to provide you with scrolling slides... I will take a look here to enable it again (or not, depending probably of a revisited discussion about scrolling slides... every second it pass, I am more toward banish scrolling at all, it is really a pain maintenance and have more cons that pros., but that;s another discussion).

**Comment by jakirkham** [comment]
@damianavila, I can understand arguing against scrolling slide from pedagogical point of view, as well. Unfortunately, `git status` in the non-short mode is a bit verbose and using the shortened mode with beginners seems mean. Maybe if I could cut down the font size use by nbviewer online, then it wouldn't be necessary. Is there an easy way to do that?

**Comment by damianavila** [comment]
>Is there an easy way to do that? 

Not a simple fix I am aware of in nbviewer... you can always patch on the fly... but that's really ugly and temporary...

**Comment by bollwyvl** [comment]
GAH! My bane.

For now, non-scrolling slides are a bug. Made #506. Will get on this this evening.

@jakirkham For right now, instead of scrolling the whole slide, or making the text smaller, perhaps just make long (i.e. longer than 65% of the screen) slides scrollable? 

```html
%%html
<style>
    .reveal section.present:not(.stack) {
        max-height: 960px;
        overflow-y: auto;
    }
</style>
```

You can execute this in a `skip` and it won't show up in the deck. Here's [what it looks like](
http://nbviewer.ipython.org/format/slides/urls/gist.github.com/bollwyvl/e72faee463bbce2e4284/raw/cd0e1deded3a0752bff333edaec67b2175bf1efb/slides%2520%287%29.ipynb#/11).


The scrollbar is ugly hanging out there in the middle of the slide, but it requires really evil tricks to make something stay scrollable while not showing scrollbars... but i would prefer this to the always-there, lying scrollbar that we "want" to restore in #506.

Here's [another approach](
http://nbviewer.ipython.org/format/slides/urls/gist.github.com/bollwyvl/e72faee463bbce2e4284/raw/73492812dab095620a37d26750dedcdd465f8dc5/slides%2520%288%29.ipynb#/11):

```html
%%html
<style>
    .reveal section.present:not(.stack) {
        max-height: 960px;
        overflow-y: hidden;
    }
    .reveal section.present:not(.stack):hover {
        overflow-y: auto;
    }
</style>
```

this hides the scrollbar until you hover over it.... which really ain't that bad, to my eye. But unusable on mobile, as there is no hover. So you could put a media selector on it. Sigh.

Hopefully something in there helps!

This continuing issue (and all related issues with all of our big upstreams bootstrap, fontawesome, mathjax) points to us probably needing to seek a different presentation thing... there's a lot of focus on dashboards right now, but perhaps @damianavila and i need to get together and gather some feedback from users like you!

**Comment by jakirkham** [comment]
Thanks for all the pointers @bollwyvl. I got something to work based off of your gist. Here's the branch to look for if you are curious ( https://github.com/jakirkham/git_ready/tree/workaround_scrolling_issue ).

I failed to get the example you showed here to work. Online, I was seeing this error ( https://github.com/jupyter/nbviewer/issues/504 ). Locally, I just wasn't seeing the scroll bars, but I could have made a mistake somewhere. This is the first commit on that branch. The working version is the second commit.
